name: Smart Commits - Advanced Jira Integration

on:
  pull_request:
    types: [closed]

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: |
          echo "This old workflow is disabled. Using jira-status-update.yml instead."
          echo "If you see this message, the new workflow should also be running."